version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/gqldb?sslmode=disable
      - SERVER_PORT=8080
      - STORAGE_TYPE=postgres
      - MIGRATIONS_PATH=/root/
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gqldb
      TZ: "Europe/Moscow"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: