// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewComment struct {
	PostID   int    `json:"postId"`
	ParentID *int   `json:"parentId,omitempty"`
	Text     string `json:"text"`
	Author   string `json:"author"`
}

type NewPost struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	Author        string `json:"author"`
	AllowComments bool   `json:"allowComments"`
}

type Query struct {
}

type Subscription struct {
}
